# Generated by Django 3.1 on 2020-12-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_myteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myteam',
            name='D',
            field=models.CharField(db_column='column5', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='K',
            field=models.CharField(db_column='column6', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='QB',
            field=models.CharField(db_column='column1', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='RB1',
            field=models.CharField(db_column='column2', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='TE',
            field=models.CharField(db_column='column4', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='WR',
            field=models.CharField(db_column='column3', max_length=80, null=True),
        ),
    ]
