# Generated by Django 3.1 on 2020-12-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20201203_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myteam',
            name='D',
            field=models.CharField(max_length=80, null=True, verbose_name='d'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='K',
            field=models.CharField(max_length=80, null=True, verbose_name='k'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='QB',
            field=models.CharField(max_length=80, null=True, verbose_name='qb'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='RB1',
            field=models.CharField(max_length=80, null=True, verbose_name='rb'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='TE',
            field=models.CharField(max_length=80, null=True, verbose_name='te'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='WR',
            field=models.CharField(max_length=80, null=True, verbose_name='wr'),
        ),
    ]
