# Generated by Django 3.1 on 2020-12-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20201203_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myteam',
            name='D',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='K',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='QB',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='RB1',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='TE',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='WR',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
