# Generated by Django 3.1 on 2020-12-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20201203_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='kicker',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterback',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runningback',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tightend',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widereceiver',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
