# Generated by Django 3.1 on 2020-12-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20201206_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myteam',
        ),
    ]
