# Generated by Django 3.1 on 2020-12-14 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20201210_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=255)),
                ('kicker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.kicker')),
                ('quarter_back', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.quarterback')),
                ('running_back', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.runningback')),
                ('tight_end', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.tightend')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wide_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.widereceiver')),
            ],
        ),
    ]
