# Generated by Django 3.1 on 2020-12-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20201215_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamscore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
